
(task "default" is
      (if (not (isSnowLeopard))
          (then (SH "cd libinject; nuke")))
      (SH "cd NuConsole; nuke")
      (SH "cd NuInject; nuke"))

(task "clobber" is
      (if (not (isSnowLeopard))
          (then (SH "cd libinject; nuke clobber")))
      (SH "cd NuConsole; nuke clobber")
      (SH "cd NuInject; nuke clobber"))

(task "clean" is
      (if (not (isSnowLeopard))
          (then (SH "cd libinject; nuke clean")))
      (SH "cd NuConsole; nuke clean")
      (SH "cd NuInject; nuke clean"))
