
(set @nu_files (filelist "^nu/.*\.nu$")) 	;; don't forget that filelist expects regular expressions.

(set @application "Growler")
(set @application_identifier "nu.programming.growler")

(application-tasks)

(task "default" => "application")
