#define NU_VERSION "0.9.1"
#define NU_VERSION_MAJOR 0
#define NU_VERSION_MINOR 9
#define NU_VERSION_TWEAK 1
#define NU_RELEASE_DATE "2010-7-17"
#define NU_RELEASE_YEAR  2010
#define NU_RELEASE_MONTH 7
#define NU_RELEASE_DAY   17
