#define NU_VERSION "0.1.4"
#define NU_VERSION_MAJOR 0
#define NU_VERSION_MINOR 1
#define NU_VERSION_TWEAK 4
#define NU_RELEASE_DATE "2007-10-11"
#define NU_RELEASE_YEAR  2007
#define NU_RELEASE_MONTH 10
#define NU_RELEASE_DAY   11
