#define NU_VERSION "0.3.2"
#define NU_VERSION_MAJOR 0
#define NU_VERSION_MINOR 3
#define NU_VERSION_TWEAK 2
#define NU_RELEASE_DATE "2008-6-8"
#define NU_RELEASE_YEAR  2008
#define NU_RELEASE_MONTH 6
#define NU_RELEASE_DAY   8
