;; Nukefile for Nu demo application

;; source files
(set @nu_files 	  (filelist "^nu/.*nu$"))

;; application description
(set @application 	       	   "Currency Converter")
(set @application_identifier   "nu.programming.currencyconverter")

;; tasks
(application-tasks)
(task "default" => "application")
