
(set platform "iPhoneOS")

;; source files
(set @c_files      (filelistWithRoot "^objc/.*\.c$" ".."))
(set @m_files      (filelistWithRoot "^objc/.*\.m$" ".."))

(case platform
      
      ("iPhoneOS"
                 (set PLATFORM "-isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS2.0.sdk")
                 (set @arch '("armv6"))
                 (set @cc "/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.0")
                 (set @library_extras "platforms/iPhoneOS/libffi/*.o platforms/iPhoneOS/pcre/*.o"))
      
      ("iPhoneSimulator" ;; this is broken, please submit fixes if you make them.
           (set PLATFORM "-isysroot /Developer/Platforms/AspenSimulator.platform/Developer/SDKs/AspenSimulator1.2.sdk")
           (set @arch '("i386")))
      
      (else nil))

(set @cflags "-g -Iinclude -I../include -DDARWIN -DIPHONE -DMACOSX -std=gnu99 #{PLATFORM}  -mmacosx-version-min=10.5")

;; library description
(set @library "libNu")

(compilation-tasks)
(library-tasks)

(task "default" => "library")

(task "clobber" => "clean" is
      (SH "rm -rf libNu.a"))
