#!/bin/sh
#
# Install the Nu TextMate bundle from Jason Sallis' GitHub repository.
# Warning: This will remove any existing Nu.tmbundle.
#
rm -rf ~/"Library/Application Support/TextMate/Bundles/Nu.tmbundle"
mkdir -pv ~/"Library/Application Support/TextMate/Bundles/"
cd ~/"Library/Application Support/TextMate/Bundles/"
git clone git://github.com/jsallis/nu.tmbundle.git "Nu.tmbundle"
osascript -e 'tell app "TextMate" to reload bundles'
