<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string></string>
	<key>fileTypes</key>
	<array>
		<string>nu</string>
		<string>Nukefile</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bnush\b</string>
	<key>foldingStartMarker</key>
	<string>\(</string>
	<key>foldingStopMarker</key>
	<string>\)</string>
	<key>keyEquivalent</key>
	<string>^~@n</string>
	<key>name</key>
	<string>Nu</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:nil|self|super)\b</string>
			<key>name</key>
			<string>constant.language.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|-?(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>'(.|(\\.*))'</string>
			<key>name</key>
			<string>constant.character.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.hash.nu</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nu</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nu</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.nu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.nu</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;&lt;[+-](.*)</string>
			<key>end</key>
			<string>\1</string>
			<key>name</key>
			<string>string.unquoted.heredoc.nu</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(/)(?=[^ ])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.regex.begin.nu</string>
				</dict>
			</dict>
			<key>end</key>
			<string>/[a-z]*</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.regex.end.nu</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.regex.nu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\/</string>
					<key>name</key>
					<string>constant.character.escape.nu</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(class)\s+((\w|\-|\!|\?)*)(\s+(is)\s+((\w|\-|\!|\?)*))?</string>
			<key>name</key>
			<string>meta.class.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([ic]?method)\s+((\w|\-|\!|\?)*)(\s+(is)\s+((\w|\-|\!|\?)*))?</string>
			<key>name</key>
			<string>meta.method.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(function|macro)\s+((\w|\-|\!|\?)*)</string>
			<key>name</key>
			<string>meta.function.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:let|set|global|cond|case|do|loop|until|while|for|break|continue|if|else|then|unless|try|throw|catch)\b</string>
			<key>name</key>
			<string>keyword.control.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:eq|neq|and|or|synchronized)\b</string>
			<key>name</key>
			<string>keyword.operator.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:append|atom|cons|car|cdr|context|eval|head|quote|parse|progn|send|tail|load|system|puts|help|version|beep)\b</string>
			<key>name</key>
			<string>support.function.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:assert_equal|assert_not_equal|assert_throws|assert_in_delta)\b</string>
			<key>name</key>
			<string>support.function.testing.nu</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nu</string>
	<key>uuid</key>
	<string>F8A96494-C89A-4CA4-A2D3-6A5A4ED56FD7</string>
</dict>
</plist>
